package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/kwangsing3/stock-bar/dbhandler"
	"github.com/kwangsing3/stock-bar/graph/model"
)

// CreateStock is the resolver for the createStock field.
func (r *mutationResolver) CreateStock(ctx context.Context, input model.NewStock) (*model.Stock, error) {
	res, err := dbhandler.DB.UpsertStock(input)
	return res, err
}

// DeleteStock is the resolver for the deleteStock field.
func (r *mutationResolver) DeleteStock(ctx context.Context, code string) (*bool, error) {
	res, err := dbhandler.DB.DeleteStock(code)
	bol := res.DeletedCount > 0
	return &bol, err
}

// InsertRecord is the resolver for the insertRecord field.
func (r *mutationResolver) InsertRecord(ctx context.Context, input model.NewRecord) (*model.DailyRecord, error) {
	data := model.DailyRecord{
		Date:          input.Date,
		TradingVolume: input.TradingVolume,
		TradingPrice:  input.TradingPrice,
		OpenPrice:     input.OpenPrice,
		HighestPrice:  input.HighestPrice,
		LowestPrice:   input.LowestPrice,
		ClosePrice:    input.ClosePrice,
		PriceDiff:     input.PriceDiff,
		TransAmount:   input.TransAmount,
	}
	_, err := dbhandler.DB.InsertRecord(input.Code, data)
	if err != nil {
		return nil, err
	}
	return &data, err
}

// DeleteRecord is the resolver for the deleteRecord field.
func (r *mutationResolver) DeleteRecord(ctx context.Context, input model.DeleteRecord) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRecord - deleteRecord"))
}

// Stock is the resolver for the stock field.
func (r *queryResolver) Stock(ctx context.Context, code string) ([]*model.Stock, error) {
	res, err := dbhandler.DB.GetStockByCode(code)
	return res, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
